AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Moneyzent API - Lambda Deployment

Parameters:
  Environment:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - prod
  CorsOrigin:
    Type: String
    Description: Allowed CORS origin for the frontend
  DeployNonce:
    Type: String
    Default: ""
    Description: Unique value to force stack updates
  ApiDomainName:
    Type: String
    Description: Custom domain name for the API (e.g. api-staging.moneyzent.com)

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: nodejs24.x
    Architectures:
      - arm64

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-moneyzent-api
      Handler: dist/bundle.handler
      CodeUri: .
      Description: Moneyzent API NestJS Application

      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - !Ref CorsOrigin
          AllowHeaders:
            - Content-Type
            - Authorization
            - X-Request-Id
          AllowMethods:
            - '*'
          AllowCredentials: true
          MaxAge: 86400

      Environment:
        Variables:
          NODE_ENV: production
          APP_ENV: !Ref Environment
          CORS_ORIGIN: !Ref CorsOrigin
          DEPLOY_NONCE: !Ref DeployNonce
          DATABASE_URL: !Sub "{{resolve:secretsmanager:${Environment}/moneyzent/api:SecretString:DATABASE_URL}}"
          BETTER_AUTH_SECRET: !Sub "{{resolve:secretsmanager:${Environment}/moneyzent/api:SecretString:BETTER_AUTH_SECRET}}"
          BETTER_AUTH_URL: !Sub "{{resolve:secretsmanager:${Environment}/moneyzent/api:SecretString:BETTER_AUTH_URL}}"

      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${Environment}/moneyzent/*

    Metadata:
      BuildMethod: makefile

  ApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref ApiDomainName
      ValidationMethod: DNS

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub ${Environment}-moneyzent-api
        Aliases:
          - !Ref ApiDomainName
        Origins:
          - Id: LambdaFunctionUrl
            DomainName: !Select [2, !Split ["/", !GetAtt ApiFunctionUrl.FunctionUrl]]
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: LambdaFunctionUrl
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled
          OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac # AllViewerExceptHostHeader
        ViewerCertificate:
          AcmCertificateArn: !Ref ApiCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        HttpVersion: http2and3

Outputs:
  FunctionUrl:
    Description: Lambda Function URL (use this as your API endpoint)
    Value: !GetAtt ApiFunctionUrl.FunctionUrl

  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ApiFunction.Arn

  CloudFrontDomainName:
    Description: CloudFront distribution domain name (set CNAME to this at your DNS provider)
    Value: !GetAtt CloudFrontDistribution.DomainName

  ApiDomain:
    Description: Custom API domain
    Value: !Ref ApiDomainName
