export const SEED_PAYEES = [
	"Acme Corp Payroll",
	"Side Hustle Platform",
	"Freelance Client A",
	"Whole Foods Market",
	"Trader Joes",
	"Costco Wholesale",
	"Target",
	"Walmart Supercenter",
	"Starbucks Reserve",
	"Blue Bottle Coffee",
	"Morning Brew Cafe",
	"Shell Gas",
	"Chevron Fuel",
	"Blue Line Metro",
	"SwiftRide",
	"Lyft",
	"Uber",
	"Delta Airlines",
	"Marriott Hotels",
	"Hilton Hotels",
	"Home Depot",
	"Lowe's",
	"Ikea",
	"Best Buy",
	"Apple Store",
	"Urban Outfitters",
	"Gap",
	"Nike",
	"Adidas",
	"Barnes & Noble",
	"GameStop",
	"Netflix",
	"Spotify",
	"Hulu",
	"Disney+",
	"Prime Video",
	"AT&T Wireless",
	"Verizon Fios",
	"Comcast Internet",
	"City Rentals",
	"Pulse Fitness",
	"Anytime Fitness",
	"CVS Pharmacy",
	"Walgreens",
	"Doctor Care Clinic",
	"Smile Dental",
	"Therapy Center",
	"PetSmart",
	"Petco",
	"Red Cross Donation",
	"Crowdfund Local",
	"Staples Office Supplies",
	"ByteCloud",
	"Figma",
	"Notion Labs",
	"Google Workspace",
	"Azure Cloud",
	"AWS",
	"Canva Pro",
	"Uber Eats",
	"DoorDash",
	"Dominos Pizza",
	"Sushi Central",
	"Taco Palace",
	"Cava",
	"Chipotle",
	"Parking Authority",
	"Bike Share City",
	"City Water",
	"City Electric",
	"Waste Management",
	"Metropolitan Insurance",
	"Chase Bank Fees",
	"Vanguard Investments",
	"Robinhood Markets",
	"Stripe Refunds",
	"Acorns Interest",
	"Workshop Hub",
	"Coursera",
	"Udemy",
	"Adobe Creative Cloud",
	"Dropbox Storage",
	"Marshalls",
	"TJ Maxx",
	"REI Co-op",
	"Wayfair",
	"HomeGoods",
	"Bed Bath & Beyond",
];
